<?php
/* @var $container Zend\Navigation\Navigation */
$container = $this->container;
?>
<ul class="<?php echo $this->navigation()->menu()->getUlClass(); ?>">
    <?php foreach ($container as $page): ?>
        <?php if (!$this->navigation()->accept($page)) continue; ?>
        <?php /* @var $page Zend\Navigation\Page\Mvc */ ?>
        <?php $hasChildren = $page->hasPages(); ?>
        <?php if (!$hasChildren): ?>
            <li<?php if ($page->isActive()) echo ' class="active"' ?>>
                <a
                    href="<?php echo $page->getHref() ?>"
                    <?php if ($page->getTarget() != ""): ?>
                        target="<?php echo $page->getTarget(); ?>"
                    <?php endif; ?>
                    >
                    <?php if ($page->get("icon") !== ""): ?>
                        <i class="<?php echo $page->get("icon"); ?>"></i>
                    <?php endif; ?>
                    <span class="mm-text"><?php echo $page->getLabel(); ?></span>
                </a>
            </li>
        <?php else: ?>
            <?php
            //check if access is allowed at least one item
            $access = false;
            foreach ($page->getPages() as $child) {
                if ($this->navigation()->accept($child) && $child->get("separator") !== true) {
                    $access = true;
                }
            }
            if ($access) :
                ?>
                <li class="dropdown<?php if ($page->isActive(true)) echo ' active' ?>">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <?php if ($page->get("icon") !== ""): ?>
                            <i class="<?php echo $page->get("icon"); ?>"></i>
                        <?php endif; ?>
                        <span>
                            <?php echo $page->getLabel(); ?>
                        </span>
                        <i class="fa fa-angle-left pull-right"></i>
                    </a>
                    <ul class="treeview-menu <?php if ($page->isActive(true)) echo 'menu-open' ?>" <?php if (!$page->isActive(true)) echo 'style="display: none;"' ?>>
                        <?php foreach ($page->getPages() as $child): ?>
                            <?php if (!$this->navigation()->accept($child)) continue; ?>
                            <?php if ($child->get("separator") === true): ?>
                                <li class="divider"></li>
                                <?php
                                continue;
                            endif;
                            ?>
                            <li<?php if ($child->isActive()) echo ' class="active"' ?>>
                                <a
                                    href="<?php echo $child->getHref() ?>"
                                    <?php if ($child->getTarget() != ""): ?>
                                        target="<?php echo $child->getTarget(); ?>"
                                    <?php endif; ?> >
                                    <?php if ($child->get("icon") !== ""): ?>
                                        <i class="<?php echo $child->get("icon"); ?>"></i>
                                    <?php endif; ?>
                                    <?php echo $child->getLabel(); ?>
                                </a>
                            </li>
                        <?php endforeach ?>
                    </ul>
                </li>
            <?php endif; ?>
        <?php endif ?>
    <?php endforeach ?>
</ul>

